Repository BotBuilderCommunity/botbuilder-community-js, pull requests merged in 2018-10, with the labels that each got.

#18 Rough draft implementation of the test of the Text Analytics APIs
  README.md
  libraries/botbuilder-sentiment-middleware/README.md
  libraries/botbuilder-sentiment-middleware/src/index.ts
  libraries/botbuilder-text-analytics-middleware/.gitignore
  libraries/botbuilder-text-analytics-middleware/README.md
  libraries/botbuilder-text-analytics-middleware/package-lock.json
  libraries/botbuilder-text-analytics-middleware/package.json
  libraries/botbuilder-text-analytics-middleware/src/entity.ts
  libraries/botbuilder-text-analytics-middleware/src/index.ts
  libraries/botbuilder-text-analytics-middleware/src/keyPhrases.ts
  libraries/botbuilder-text-analytics-middleware/src/languageDetection.ts
  libraries/botbuilder-text-analytics-middleware/src/sentiment.ts
  libraries/botbuilder-text-analytics-middleware/test/README.md
  libraries/botbuilder-text-analytics-middleware/test/bot.js
  libraries/botbuilder-text-analytics-middleware/test/botbuilder-sentiment-middleware-testbot.bot
  libraries/botbuilder-text-analytics-middleware/test/package-lock.json
  libraries/botbuilder-text-analytics-middleware/test/package.json
  libraries/botbuilder-text-analytics-middleware/test/test.js
  libraries/botbuilder-text-analytics-middleware/tsconfig.json
Labels: enhancement

#20 A bunch of new prompts
  .vscode/launch.json
  README.md
  libraries/botbuilder-dialog-prompts/.gitignore
  libraries/botbuilder-dialog-prompts/README.md
  libraries/botbuilder-dialog-prompts/package-lock.json
  libraries/botbuilder-dialog-prompts/package.json
  libraries/botbuilder-dialog-prompts/src/email.ts
  libraries/botbuilder-dialog-prompts/src/guid.ts
  libraries/botbuilder-dialog-prompts/src/index.ts
  libraries/botbuilder-dialog-prompts/src/internet.ts
  libraries/botbuilder-dialog-prompts/src/numberWithType.ts
  libraries/botbuilder-dialog-prompts/src/numberWithUnit.ts
  libraries/botbuilder-dialog-prompts/src/phone.ts
  libraries/botbuilder-dialog-prompts/src/socialMedia.ts
  libraries/botbuilder-dialog-prompts/test/botbuilder-dialog-prompts-testbot.bot
  libraries/botbuilder-dialog-prompts/test/index.js
  libraries/botbuilder-dialog-prompts/test/package-lock.json
  libraries/botbuilder-dialog-prompts/test/package.json
  libraries/botbuilder-dialog-prompts/test/test.js
  libraries/botbuilder-dialog-prompts/tsconfig.json
  libraries/botbuilder-test/README.md
Labels: enhancement, help wanted, test

#25 Update all README files to enable code highlighting on Github
  libraries/botbuilder-config/README.md
  libraries/botbuilder-dialog-prompts/README.md
  libraries/botbuilder-text-analytics-middleware/README.md
Labels: enhancement

#23 Add CODEOWNERS file
  CODEOWNERS
Labels: question
